name: sim_detector_platform_interface
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/afmjoaa/sim_detector.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.0.0
  plugin_platform_interface: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
